---
- name: Ensure keepalived is installed
  package:
    name: "{{ keepalived_package_name }}"
    state: present

- name: Create keepalived config file
  template:
    src: "etc/keepalived/keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
    owner: root
    group: root
    mode: 0644
  notify: Restart keepalived

- name: Create keepalived config file
  template:
    src: "etc/keepalived/keepalived.conf.bak.j2"
    dest: "/etc/keepalived/keepalived.conf"
    owner: root
    group: root
    mode: 0644
  notify: Restart keepalived
  delegate_to: Jitsi-bak

- name: Ensure keepalived is enabled and started
  service:
    name: "{{ keepalived_service_name }}"
    state: started
    enabled: yes
