---

- name: Checkout host ssh public key on the main host
  shell: cat /root/.ssh/id_rsa.pub
  register: ssh_pub_key
  delegate_to: "{{ lxc_master_server }}" #Host with file "id_rsa.pub"

- debug:
    msg: "{{ ssh_pub_key.stdout }}"

- name: Copy ssh public key to container
  shell: |
    lxc exec "{{ item.name }}" -- sh -c "echo {{ ssh_pub_key.stdout }} > /root/.ssh/authorized_keys"
  with_items: "{{ containers }}"

# - name: Delete ip address of hosts from "/root/.ssh/known_hosts"
#   shell: |
#     ssh-keygen -f "/root/.ssh/known_hosts" -R "192.172.201.209" '"{{ item.ctip }}"'
#   with_items: "{{ containers }}"
