---

- name: 4-Upgrade all packages on servers
  apt:
    upgrade: yes
    update_cache: yes
    # name: "*"
    #state: latest
  environment:
    http_proxy: "{{ proxy }}"
  delegate_to: "{{ item.ctip }}"             #was "{{ item.ctip }}"
  with_items: "{{ containers }}"

- name: 4.1-Install keepalived
  apt:
    name: keepalived
    state: present
  environment:
    http_proxy: "{{ proxy }}"
  delegate_to: "{{ item.ctip }}"            #was "{{ item.ctip }}"
  with_items: "{{ containers }}"



# - name: 4-Update and Upgrade all packages on servers
#   shell: lxc exec "{{ item.name }}" -- sh -c "apt-get update && apt-get upgrade -y"
#   with_items: "{{ containers }}"

# - name: 4.1-Install keepalived
#   shell: lxc exec "{{ item.name }}" -- sh -c "apt-get install keepalived -y"
#   with_items: "{{ containers }}"