---
# vars file for keepalived

instance_name: VI_1
instance_state_NODE1: MASTER
instance_state_NODE2: SLAVE
instance_interface: eth1
virtual_router_id: 51
instance_priority_NODE1:: 100
instance_priority_NODE2:: 150
advert_int: 1
auth_type: PASS
auth_pass: pass
virtual_ipaddress: 172.16.3.85