---
- hosts: Server-52
  gather_facts: false
  vars_files:
  - /etc/ansible/roles/lxd_qs/vars/main.yml
  - /etc/ansible/roles/lxd_qs/defaults/main.yml
  tasks:

    # - name:  Ansible Copy Directory Local /etc/ansible/roles/lxd_qs/files to Remote host
    #   include: Copying_Directory_and_contents.yaml

    # - name: Creating Cantainer Jitsi with IP 192.168.100.120
    #   include: Container_Jitsi_192.168.100.120.yaml

    # - name:  Creating Cantainer Nginx with IP  192.168.100.121
    #   include: Container_Jitsi-bak_192.168.100.121.yaml

    # - name:  Run a complex command within a "running" container
    #   include: container_command_in.yaml

    # - name:  Check and copy ssh public key to containers
    #   include: copy_ssh_to_container.yaml

    - name:  Create directory in container Jitsi-bak
      include: create_directory.yaml


