---
# tasks file for keepalived

# - name: Install dependencies
#   apt:
#     name: "{{ packages }}"
#     state: present
#   vars:
#     packages:
#       - apt-transport-https
#       - ca-certificates
#       - curl
#       - software-properties-common

- name: Add Keepalived PPA repository
  apt_repository:
    repo: ppa:keepalived/daily

- name: Update cache 
  command: apt-get update

- name: install keepalived
  ansible.builtin.package:
    name: keepalived
    state: present

- name: service | enabling keepalived on boot and start
  service:
    name: keepalived
    state: started
    enabled: true
  become: true