---
- hosts: devel-lxd02
  gather_facts: false
  vars_files:
  - /etc/ansible/roles/lxd_qs/vars/main.yml
  - /etc/ansible/roles/lxd_qs/defaults/main.yml
  tasks:

    - name: Create directory
      file:
        path: /tmp/{{ lxc_CT_NAME2 }}
        state: directory