---
- name: check out host ssh public key
  shell: cat /root/.ssh/id_rsa.pub
  register: ssh_pub_key

- debug:
    msg: "{{ ssh_pub_key.stdout }}"

- name: copy ssh public key to container Jitsi
  shell: |
    lxc exec Jitsi -- sh -c "echo {{ ssh_pub_key.stdout }} > /root/.ssh/authorized_keys"

- name: copy ssh public key to container Jitsi-bak 
  shell: |
    lxc exec Jitsi-bak -- sh -c "echo {{ ssh_pub_key.stdout }} > /root/.ssh/authorized_keys"