---

- name: Copying the directory and contents to remote host, copy network files in LXC container (/etc/ansible/roles/lxd_qs/files)
  become: true 
  copy:
    src: "{{ lxc_src_path }}"
    dest: "{{ lxc_dest_path }}"
    owner: root
    group: root        
    mode: 0644
  delegate_to: "{{ item }}"
  with_items:
    - devel-lxd01
    - devel-lxd02
