---
- hosts: devel-lxd02
  gather_facts: false
  vars_files:
  - /etc/ansible/roles/lxd_qs/vars/main.yml
  - /etc/ansible/roles/lxd_qs/defaults/main.yml
  tasks:

    - name: Run a command in a container and then restart it
      community.general.lxc_container:
        name: Jitsi-bak
        state: restarted
        container_command: |
          echo 'hello world.' | tee /opt/restarted
