- name: List name of LXC network file in Jitsi_bak LXC path /etc/netplan/
  shell: lxc exec "{{ lxc_CT_NAME2 }}" ls /etc/netplan/
  register: file_of_Jitsi_bak

- debug:
    msg: "{{ file_of_Jitsi_bak.stdout }}"

- name: Using template to copy a file from hostin folder /tmp/ with name of file netplan from LXC container
  ansible.builtin.template:
    src: /etc/ansible/roles/lxd_qs/templates/{{ lxc_IP_var204 }}
    dest: /tmp/{{ file_of_Jitsi_bak.stdout }}
    owner: root
    group: root
    mode: '0644'
  delegate_to: "{{ lxc_NODE_BACKUP }}"

- name: Copy new IP to container Jitsi_bak from /tmp/ folder in host
  shell: |
    lxc file push /tmp/{{ file_of_Jitsi_bak.stdout }} local:"{{ lxc_CT_NAME2 }}"/etc/netplan/"{{ file_of_Jitsi_bak.stdout }}"
    lxc exec "{{ lxc_CT_NAME2 }}" netplan apply

- name: Show us new IP of Jitsi_bak container
  shell: lxc exec "{{ lxc_CT_NAME2 }}" -- ip addr show eth1 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1
  register: ip_of_container_Jitsi_bak

- debug:
    msg: "{{ ip_of_container_Jitsi_bak.stdout }}"
